@MechanicsWorkshopApi_HostAddress = https://localhost:7113

GET {{MechanicsWorkshopApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MechanicsWorkshopApi_HostAddress}}/weatherforecast

###
